# -*- coding: utf-8 -*-
"""market_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PCRlouSetfmYXb9bJr1tmoq8SPumdmUR
"""

#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#read data set
data = pd.read_csv('/content/online.csv')
data

data.isnull().sum()

data.isnull().any()

#if has null valu
#null_valu = data.Transport.mean()
#data.Transport = data.Transport.fillna(null_valu)

#Separate X and Y
X = data.drop(["Profit"],axis=1)
Y = data["Profit"]

#show X
X

#show Y
Y

#Encoding the categorical variable use one hot encoding
city = pd.get_dummies(X["Area"],drop_first=True)
city

#drop area column beacuse we create already 3 column with Onehot encoding
X = X.drop("Area",axis=1)

X

#concatation
X = pd.concat([X,city],axis=1)

X

#import Library
from sklearn.model_selection import train_test_split
#split training and test data
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.25, random_state=140)

#fiting multiple linear regression model to training set
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(xtrain,ytrain)

ytest

#predicted the test set result
predict = regressor.predict(xtest)
predict

#R Squared Valu calculation for accuracy score
from sklearn.metrics import r2_score
score = r2_score(ytest,predict)
score